### ISSUE TITLE
Questions about Evaluation Metric

### ISSUE THREAD

**Issue by zycheiheihei** [philippe-eecs/IDQL#3]
Hi, I'm wondering what is the evaluation metric of IDQL for D4RL benchmarks. Does it report the max averaged return during training for every individual run or does it report the score at the last training step for all random seeds?   Thanks a lot.

**Comment by philippe-eecs** [comment]
I took the average of the last evaluation over the seeds I ran. There is quite a bit of variance in the seeds (like +-5 to +-10).

I don't take the max evaluation. Some papers do this however...

**Comment by zycheiheihei** [comment]
Thanks for your immediate reply!
